### PR TITLE
Update feeds.xml

### PR DESCRIPTION
**Pull request by glaucusec**
[RestorePrivacy](https://restoreprivacy.com/) contains privacy and security news, original research, and in-depth resources. It is added to the `🔒 Infosec | Privacy` section.

### CODE REVIEW

**Comment by phretor** [comment]
Thanks @glaucusec - I didn't know this source. From your experience, is it privacy focused or rather on the generic cybersecurity (including privacy) side?

**Comment by glaucusec** [comment]
> Thanks @glaucusec - I didn't know this source. From your experience, is it privacy focused or rather on the generic cybersecurity (including privacy) side?

I don't think its just privacy focused. It inlcudes news related to infosec and also privacy. Some of the latest ones are [RansomHouse Cyber Gang Claims Ipca Laboratories as Latest Victim](https://restoreprivacy.com/ransomhouse-ipca-laboratories-breach/), [Verified Twitter Vulnerability Exposes Data from 5.4 Million Accounts](https://restoreprivacy.com/twitter-vulnerability-exposes-5-million-accounts/). In depth researches on certain topics and very well written `how-to-guides` and also certain reviews on open-source apps and services. If you are just looking for news this is the [link](https://restoreprivacy.com/category/news-reports/)

**Comment by phretor** [comment]
Then it's probably a better fit for "Infosec | Generic News"? If that looks good to you, please feel free to add a new commit to this PR and I'll happily accept it. Please, feel free to add yourself to the README under the contributors/credits :-)

**Comment by glaucusec** [comment]
Okay

**Comment by glaucusec** [comment]
A new commit will be visible now. Thanks

**Comment by phretor** [comment]
LGTM

**Pull request merged**
